### ISSUE TITLE
label:question

### ISSUE THREAD

**Issue by Electrik-rich546456** [ruromgar/python-ai-trading-system#1]
This is a really great idea. I've been trying to make my own bot for a very long time but i'm still only learning python. seeing your code I hope you can help me make the changes i want.
what lines do I need to change to use this [API](https://github.com/bitfinexcom/bitfinex-api-py) instead ?

**Comment by ruromgar** [comment]
hey there, thanks for the feedback! that API looks crypto-specific. In my code everything related to trading is done with the `trade_robinhood()` and `trade_alpaca()` functions - you'd need to define your own function for that API.

**Comment by Electrik-rich546456** [comment]
Could you help me do that please. my discord is @Happy67586

**Comment by ruromgar** [comment]
Hey - I don't really use discord for anything besides casual gaming (: what exactly do you want to do?

**Comment by Electrik-rich546456** [comment]
Hi. Can we chat privately somehow?

**Comment by ruromgar** [comment]
Sure, just send me a mail to ruromgar [at] gmail [dot] com. I'm closing this :)
